version: '3.9'
services:
  keycloak:
    image: "jboss/keycloak"
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER : divya
      KEYCLOAK_PASSWORD : sharma